language: node_js
node_js:
  - "stable"
sudo: false
cache:
  directories:
    - docs/node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_6ddbe33ab8fb_key -iv $encrypted_6ddbe33ab8fb_iv -in ie_travis_gh_deploy_key.enc -out ie_travis_deploy_key -d
  - chmod 600 ie_travis_deploy_key
  - eval `ssh-agent -s`
  - ssh-add ie_travis_deploy_key
install:
- pushd .
- cd ${DIR_TEMPLATE}
- npm install -g gitbook-cli
- npm install
- which gitbook
- popd
branches:
  only:
    - master
    - add-docs
script:
- pushd .
- cd ${DIR_TEMPLATE}
- gitbook install
- gitbook build
- git push origin --delete gh-pages
- pushd .
- cd _book
- git init
- git checkout -b gh-pages
- git add .
- git commit -m "Publishing site on `date "+%Y-%m-%d %H:%M:%S"`"
- git push git@github.com:${GH_REPO}.git gh-pages
- popd
- rm -rf _book
- popd
before_deploy:
- git config --global user.email "muew@jp.ibm.com"
- git config --global user.name "Yuji Watanabe"
- git config --global push.default simple
env:
  global:
  - DIR_TEMPLATE=docs
  - GH_REPO=IBM/integrity-enforcer
notifications:
  slack: ibm-research:2UrL2yS56MYEnX9iWSKXIzEd%