kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: integrity-enforcer-operator
subjects:
- kind: ServiceAccount
  name: integrity-enforcer-operator
  namespace: integrity-enforcer-ns
roleRef:
  kind: ClusterRole
  name: integrity-enforcer-operator
  apiGroup: rbac.authorization.k8s.io
